{ ... }: {
    xdg.configFile = {
        "libfm/libfm.conf".text = ''
            # Configuration file for the libfm version 1.4.0.
            # Autogenerated file, don't edit, your changes will be overwritten.

            [config]
            single_click=0
            middle_click=0
            use_trash=1
            confirm_del=1
            confirm_trash=1
            advanced_mode=0
            si_unit=0
            force_startup_notify=1
            date_iso_8601=0
            backup_as_hidden=1
            no_usb_trash=1
            no_child_non_expandable=0
            show_full_names=1
            only_user_templates=0
            template_run_app=0
            template_type_once=0
            auto_selection_delay=600
            drop_default_action=auto
            defer_content_test=0
            quick_exec=0
            terminal=foot
            archiver=xarchiver
            thumbnail_local=1
            thumbnail_max=2048
            smart_desktop_autodrop=1

            [ui]
            big_icon_size=48
            small_icon_size=16
            pane_icon_size=16
            thumbnail_size=128
            show_thumbnail=1
            shadow_hidden=1

            [places]
            places_home=1
            places_desktop=0
            places_root=1
            places_computer=0
            places_trash=1
            places_applications=1
            places_network=0
            places_unmounted=1
        '';
        "pcmanfm/default/pcmanfm.conf".text = ''
            [config]
            bm_open_method=0

            [volume]
            mount_on_startup=1
            mount_removable=1
            autorun=1

            [ui]
            always_show_tabs=0
            max_tab_chars=32
            win_width=950
            win_height=1034
            splitter_pos=150
            media_in_new_tab=0
            desktop_folder_new_win=0
            change_tab_on_drop=1
            close_on_unmount=1
            focus_previous=0
            side_pane_mode=places
            view_mode=list
            show_hidden=0
            sort=name;ascending;
            toolbar=newtab;navigation;home;
            show_statusbar=1
            pathbar_mode_buttons=0
        '';
        "xarchiver/xarchiverrc".text = ''
            [xarchiver]
            preferred_format=23
            prefer_unzip=true
            confirm_deletion=true
            sort_filename_content=false
            advanced_isearch=true
            auto_expand=true
            store_output=false
            icon_size=2
            show_archive_comment=false
            show_sidebar=true
            show_location_bar=true
            show_toolbar=true
            preferred_custom_cmd=
            preferred_temp_dir=/tmp
            preferred_extract_dir=/home/che/Downloads
            allow_sub_dir=0
            extended_dnd=1
            ensure_directory=true
            overwrite=false
            full_path=2
            touch=false
            fresh=false
            update=false
            store_path=false
            updadd=true
            freshen=false
            recurse=true
            solid_archive=false
            remove_files=false
        '';
    };
}
